# Lab 2

About: TODO 

The problems in the lab are about arrays and array manipulations... 

Goal: TODO 

Starting next week we will studying a related package for table manipulation. We want to learn how to access, filter, slice...

Deadline: TODO

Due by 11:59pm on ...

Submission Instructions: TODO

Save as from class_share...  

### Lists

Write a function `average` that takes a number and returns the average of all inputs on which it has ever been called. *Challenge:* Can you do it without any global names besides `average`?

```
BEGIN QUESTION
name: q1c
```

In [18]:
def average(n):
    """Return the average of all arguments ever passed to the average function.
    
    >>> average(1)
    1.0
    >>> average(3)
    2.0
    >>> average(8)
    4.0
    >>> average(0)
    3.0
    """
    # BEGIN SOLUTION
    average.total += n
    average.k += 1
    return average.total / average.k
average.total, average.k = 0, 0
    # END SOLUTION
# Please don't call average here, or you'll confuse the automated tests.

In [19]:
# TEST
average(1)

1.0

In [20]:
# TEST
average(3)

2.0

In [21]:
# TEST
average(8)

4.0

In [22]:
# TEST
average(0)

3.0

### Arrays

#### Question 2

The core of NumPy is the array. Like Python lists, arrays store data; however, they store data in a more efficient manner. In many cases, this allows for faster computation and data manipulation.

In Data 8, we used `make_array` from the `datascience` module, but that's not the most typical way. Instead, use `np.array` to create an array. It takes a sequence, such as a list or range. 

Below, create an array `arr` containing the values 1, 2, 3, 4, and 5 (in that order).

```
BEGIN QUESTION
name: q2
```

In [23]:
arr = np.array([1, 2, 3, 4, 5]) # SOLUTION

In [24]:
# TEST
arr

array([1, 2, 3, 4, 5])

In [25]:
# TEST
type(arr) is np.ndarray

True

In addition to values in the array, we can access attributes such as shape and data type. A full list of attributes can be found [here](https://docs.scipy.org/doc/numpy-1.15.0/reference/arrays.ndarray.html#array-attributes).

In [26]:
arr[3]

4

In [27]:
arr[2:4]

array([3, 4])

In [28]:
arr.shape

(5,)

In [29]:
arr.dtype

dtype('int64')

Arrays, unlike Python lists, cannot store items of different data types.

In [30]:
# A regular Python list can store items of different data types
[1, '3']

[1, '3']

In [31]:
# Arrays will convert everything to the same data type
np.array([1, '3'])

array(['1', '3'], dtype='<U21')

In [32]:
# Another example of array type conversion
np.array([5, 8.3])

array([5. , 8.3])

Arrays are also useful in performing *vectorized operations*. Given two or more arrays of equal length, arithmetic will perform element-wise computations across the arrays. 

For example, observe the following:

In [33]:
# Python list addition will concatenate the two lists
[1, 2, 3] + [4, 5, 6]

[1, 2, 3, 4, 5, 6]

In [34]:
# NumPy array addition will add them element-wise
np.array([1, 2, 3]) + np.array([4, 5, 6])

array([5, 7, 9])

#### Question 3a

Given the array `random_arr`, assign `valid_values` to an array containing all values $x$ such that $2x^4 > 1$.

```
BEGIN QUESTION
name: q3a
```

In [35]:
np.random.seed(42)
random_arr = np.random.rand(60)
valid_values = random_arr[(2 * random_arr  ** 4 > 1)] # SOLUTION

In [36]:
# TEST
valid_values

array([0.95071431, 0.86617615, 0.96990985, 0.94888554, 0.96563203,
       0.9093204 , 0.96958463, 0.93949894, 0.89482735, 0.92187424])

#### Question 3b

Use NumPy to recreate your answer to Question 1b. The input parameters will both be lists, so you will need to convert the lists into arrays before performing your operations.

**Hint:** Use the [NumPy documentation](https://docs.scipy.org/doc/numpy-1.15.1/reference/index.html). If you're stuck, try a search engine! Searching the web for examples of how to use modules is very common in data science.

```
BEGIN QUESTION
name: q3b
```

In [37]:
def array_sum(list_1, list_2):
    """Compute x^2 + y^3 for each x, y in list_1, list_2. 
    
    Assume list_1 and list_2 have the same length.
    
    Return a NumPy array.
    """
    assert len(list_1) == len(list_2), "both args must have the same number of elements"
    # BEGIN SOLUTION
    # Solution 1
    return np.square(list_1) + np.power(list_2, 3)
    # Solution 2
    return np.array(list_1) ** 2 + np.array(list_2) ** 3
    # END SOLUTION

In [38]:
# TEST
array_sum([1], [1])

array([2])

In [39]:
# TEST
array_sum([-1], [1])

array([2])

In [40]:
# TEST
array_sum([1], [-1])

array([0])

In [41]:
# TEST
array_sum([1, 2, 3], [1, 2, 3])

array([ 2, 12, 36])

In [42]:
# TEST
array_sum([1, 5, 2], [3, 6, 6])

array([ 28, 241, 220])

In [43]:
# TEST
type(array_sum([], [])) is np.ndarray

True

You might have been told that Python is slow, but array arithmetic is carried out very fast, even for large arrays.

For ten numbers, `list_sum` and `array_sum` both take a similar amount of time.

In [44]:
sample_list_1 = list(range(10))
sample_array_1 = np.arange(10)

In [45]:
%%time
list_sum(sample_list_1, sample_list_1)

CPU times: user 20 µs, sys: 0 ns, total: 20 µs
Wall time: 27.2 µs


[0, 2, 12, 36, 80, 150, 252, 392, 576, 810]

In [46]:
%%time
array_sum(sample_array_1, sample_array_1)

CPU times: user 26 µs, sys: 1e+03 ns, total: 27 µs
Wall time: 30 µs


array([  0,   2,  12,  36,  80, 150, 252, 392, 576, 810])

The time difference seems negligible for a list/array of size 10; depending on your setup, you may even observe that `list_sum` executes faster than `array_sum`! However, we will commonly be working with much larger datasets:

In [47]:
sample_list_2 = list(range(100000))
sample_array_2 = np.arange(100000)

In [48]:
%%time
list_sum(sample_list_2, sample_list_2)
; # The semicolon hides the output

CPU times: user 117 ms, sys: 8.47 ms, total: 126 ms
Wall time: 133 ms


In [49]:
%%time
array_sum(sample_array_2, sample_array_2)
;

CPU times: user 3.21 ms, sys: 3.35 ms, total: 6.57 ms
Wall time: 6.05 ms


With the larger dataset, we see that using NumPy results in code that executes over 50 times faster! Throughout this course (and in the real world), you will find that writing efficient code will be important; arrays and vectorized operations are the most common way of making Python programs run quickly.